apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gauth-allow-namespace
  namespace: gauth-development
spec:
  podSelector:
    matchLabels:
      app: gauth
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
        - namespaceSelector:
            matchLabels:
              name: gauth-development
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 9090
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: gauth-development
      ports:
        - protocol: TCP
          port: 5432 # Postgres
        - protocol: TCP
          port: 6379 # Redis
        - protocol: TCP
          port: 8200 # Vault
