run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/Gimel-Foundation/gauth
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  funlen:
    lines: 100
    statements: 50
  mnd:
    ignored-numbers:
      - "0"
      - "1" 
      - "2"
      - "3"
      - "4"
      - "5"
      - "8"
      - "10"
      - "16"
      - "32"
      - "64"
      - "100"
      - "200"
      - "400"
      - "401"
      - "403"
      - "404"
      - "500"
      - "1000"
      - "1024"
      - "3600"
      - "86400"

linters:
  disable-all: true
  enable:
    - bodyclose
    - dupl
    - errcheck
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - mnd
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    - path: pkg/auth/rfc_implementation\.go
      text: "is unused"
      linters:
        - unused
    - path: internal/monitoring/prometheus/exporter\.go
      text: "is unused"
      linters:
        - unused
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
