package examples
// Package examples demonstrates how to integrate the revocation system with a web server
package examples

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"time"

	"github.com/mauriciomferz/Gauth_go/pkg/revocation"
)




















































































































































































































































































































































































































































































































































































































































































































































func (l *SimpleLogger) Errorf(format string, args ...interface{}) { log.Printf("[ERROR] "+format, args...) }func (l *SimpleLogger) Error(msg string)                         { log.Println("[ERROR]", msg) }func (l *SimpleLogger) Warnf(format string, args ...interface{}) { log.Printf("[WARN] "+format, args...) }func (l *SimpleLogger) Warn(msg string)                          { log.Println("[WARN]", msg) }func (l *SimpleLogger) Infof(format string, args ...interface{}) { log.Printf("[INFO] "+format, args...) }func (l *SimpleLogger) Info(msg string)                          { log.Println("[INFO]", msg) }type SimpleLogger struct{}// SimpleLogger implements revocation.Logger interface}	}		log.Fatalf("Server failed: %v", err)	if err := http.ListenAndServe(":8081", mux); err != nil {	log.Println("Starting revocation API server on :8081")	// Start server	service.RegisterHandlers(mux)	mux := http.NewServeMux()	// Create HTTP server	defer service.Close()	}		log.Fatalf("Failed to create revocation service: %v", err)	if err != nil {	service, err := NewRevocationWebService(redisAddrs, logger)	redisAddrs := []string{"localhost:7000", "localhost:7001", "localhost:7002"}	// Initialize revocation service	logger := &SimpleLogger{}	// Logger implementationfunc ExampleWebServerIntegration() {// ExampleWebServerIntegration demonstrates complete web server integration// ============================================================================// EXAMPLE USAGE// ============================================================================}	})		"timestamp": time.Now().Unix(),		"systems": []string{"oracle", "two_phase", "optimistic", "circuit_breaker"},		"status":  "healthy",	json.NewEncoder(w).Encode(map[string]interface{}{	w.Header().Set("Content-Type", "application/json")	}		return		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodGet {func (rws *RevocationWebService) HandleHealth(w http.ResponseWriter, r *http.Request) {// GET /api/revocation/health// HandleHealth provides a health check endpoint}	})		"overall_allowed": twoPhaseUsable && optimisticUsable && circuitAllowed,		},			"message": circuitMsg,			"allowed": circuitAllowed,			"metrics": circuitMetrics,		"circuit_breaker": map[string]interface{}{		},			"message": optimisticMsg,			"usable":  optimisticUsable,			"state":   optimisticState,		"optimistic": map[string]interface{}{		},			"message": twoPhaseMsg,			"usable":  twoPhaseUsable,			"state":   twoPhaseState,		"two_phase": map[string]interface{}{		"poa_id": poaID,	json.NewEncoder(w).Encode(map[string]interface{}{	w.Header().Set("Content-Type", "application/json")	circuitAllowed, circuitMsg, _ := rws.circuitBreaker.IsPoAAllowed(ctx, poaID)	optimisticUsable, optimisticMsg, _ := rws.optimistic.IsPoAUsable(ctx, poaID)	twoPhaseUsable, twoPhaseMsg, _ := rws.twoPhase.IsPoAUsable(ctx, poaID)	// Get usability from each system	circuitMetrics, _ := rws.circuitBreaker.GetMetrics(ctx, poaID)	optimisticState, _ := rws.optimistic.GetRevocationState(ctx, poaID)	twoPhaseState, _ := rws.twoPhase.GetPoAState(ctx, poaID)	// Get all status information	ctx := r.Context()	}		return		http.Error(w, "Missing poa_id parameter", http.StatusBadRequest)	if poaID == "" {	poaID := r.URL.Query().Get("poa_id")	}		return		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodGet {func (rws *RevocationWebService) HandleGetStatus(w http.ResponseWriter, r *http.Request) {// GET /api/revocation/status?poa_id=poa-123// HandleGetStatus retrieves comprehensive revocation status for a PoA// ============================================================================// STATUS & HEALTH// ============================================================================}	})		"message": "Transaction validated successfully",		"allowed": true,	json.NewEncoder(w).Encode(map[string]interface{}{	w.WriteHeader(http.StatusOK)	w.Header().Set("Content-Type", "application/json")	// All checks passed	}		return		http.Error(w, fmt.Sprintf("Record transaction error: %v", err), http.StatusInternalServerError)		rws.logger.Errorf("Failed to record transaction: %v", err)	if err := rws.circuitBreaker.RecordTransaction(ctx, req.PoAID, req.Value, req.Success); err != nil {	// 4. Record transaction in circuit breaker	}		return		})			"message": message,			"reason":  "optimistic_revocation",			"allowed": false,		json.NewEncoder(w).Encode(map[string]interface{}{		w.WriteHeader(http.StatusForbidden)		w.Header().Set("Content-Type", "application/json")	if !usable {	}		return		http.Error(w, fmt.Sprintf("Optimistic error: %v", err), http.StatusInternalServerError)		rws.logger.Errorf("Optimistic check failed: %v", err)	if err != nil {	usable, message, err = rws.optimistic.IsPoAUsable(ctx, req.PoAID)	// 3. Check optimistic revocation	}		return		})			"message": message,			"reason":  "two_phase_revocation",			"allowed": false,		json.NewEncoder(w).Encode(map[string]interface{}{		w.WriteHeader(http.StatusForbidden)		w.Header().Set("Content-Type", "application/json")	if !usable {	}		return		http.Error(w, fmt.Sprintf("Two-phase error: %v", err), http.StatusInternalServerError)		rws.logger.Errorf("Two-phase check failed: %v", err)	if err != nil {	usable, message, err := rws.twoPhase.IsPoAUsable(ctx, req.PoAID)	// 2. Check two-phase revocation	}		return		})			"message": message,			"reason":  "circuit_breaker",			"allowed": false,		json.NewEncoder(w).Encode(map[string]interface{}{		w.WriteHeader(http.StatusForbidden)		w.Header().Set("Content-Type", "application/json")	if !allowed {	}		return		http.Error(w, fmt.Sprintf("Circuit breaker error: %v", err), http.StatusInternalServerError)		rws.logger.Errorf("Circuit breaker check failed: %v", err)	if err != nil {	allowed, message, err := rws.circuitBreaker.IsPoAAllowed(ctx, req.PoAID)	// 1. Check circuit breaker (rate limits)	ctx := r.Context()	}		return		http.Error(w, "Missing poa_id", http.StatusBadRequest)	if req.PoAID == "" {	}		return		http.Error(w, "Invalid request body", http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {	}		Success bool   `json:"success"`		Value   uint64 `json:"value"`		PoAID   string `json:"poa_id"`	var req struct {	}		return		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (rws *RevocationWebService) HandleValidateTransaction(w http.ResponseWriter, r *http.Request) {// Body: {"poa_id": "poa-123", "value": 1000000000000000000, "success": true}// POST /api/revocation/validate// HandleValidateTransaction validates a transaction against all revocation systems// ============================================================================// UNIFIED VALIDATION// ============================================================================}	})		"message": "PoA manually resumed",		"status":  "resumed",	json.NewEncoder(w).Encode(map[string]string{	w.WriteHeader(http.StatusOK)	w.Header().Set("Content-Type", "application/json")	}		return		http.Error(w, err.Error(), http.StatusInternalServerError)		rws.logger.Errorf("Failed to resume PoA %s: %v", req.PoAID, err)	if err := rws.circuitBreaker.ManualResume(ctx, req.PoAID); err != nil {	ctx := r.Context()	}		return		http.Error(w, "Missing poa_id", http.StatusBadRequest)	if req.PoAID == "" {	}		return		http.Error(w, "Invalid request body", http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {	}		PoAID string `json:"poa_id"`	var req struct {	}		return		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (rws *RevocationWebService) HandleManualResume(w http.ResponseWriter, r *http.Request) {// Body: {"poa_id": "poa-789"}// POST /api/revocation/circuit/resume// HandleManualResume manually resumes a suspended PoA (admin)}	})		"message": "PoA manually suspended",		"status":  "suspended",	json.NewEncoder(w).Encode(map[string]string{	w.WriteHeader(http.StatusOK)	w.Header().Set("Content-Type", "application/json")	}		return		http.Error(w, err.Error(), http.StatusInternalServerError)		rws.logger.Errorf("Failed to suspend PoA %s: %v", req.PoAID, err)	if err := rws.circuitBreaker.ManualSuspend(ctx, req.PoAID, reason); err != nil {	reason := revocation.SuspensionReason(req.Reason)	ctx := r.Context()	}		return		http.Error(w, "Missing required fields", http.StatusBadRequest)	if req.PoAID == "" || req.Reason == "" {	}		return		http.Error(w, "Invalid request body", http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {	}		Reason string `json:"reason"`		PoAID  string `json:"poa_id"`	var req struct {	}		return		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (rws *RevocationWebService) HandleManualSuspend(w http.ResponseWriter, r *http.Request) {// Body: {"poa_id": "poa-789", "reason": "RATE_LIMIT_TX"}// POST /api/revocation/circuit/suspend// HandleManualSuspend manually suspends a PoA (admin)}	})		"message": "Metrics reset successfully",		"status":  "reset",	json.NewEncoder(w).Encode(map[string]string{	w.WriteHeader(http.StatusOK)	w.Header().Set("Content-Type", "application/json")	}		return		http.Error(w, err.Error(), http.StatusInternalServerError)		rws.logger.Errorf("Failed to reset metrics for PoA %s: %v", req.PoAID, err)	if err := rws.circuitBreaker.ResetMetrics(ctx, req.PoAID); err != nil {	ctx := r.Context()	}		return		http.Error(w, "Missing poa_id", http.StatusBadRequest)	if req.PoAID == "" {	}		return		http.Error(w, "Invalid request body", http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {	}		PoAID string `json:"poa_id"`	var req struct {	}		return		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (rws *RevocationWebService) HandleResetMetrics(w http.ResponseWriter, r *http.Request) {// Body: {"poa_id": "poa-789"}// POST /api/revocation/circuit/reset// HandleResetMetrics resets circuit breaker metrics for a PoA (admin)}	json.NewEncoder(w).Encode(metrics)	w.Header().Set("Content-Type", "application/json")	}		return		http.Error(w, err.Error(), http.StatusInternalServerError)		rws.logger.Errorf("Failed to get metrics for PoA %s: %v", poaID, err)	if err != nil {	metrics, err := rws.circuitBreaker.GetMetrics(ctx, poaID)	ctx := r.Context()	}		return		http.Error(w, "Missing poa_id parameter", http.StatusBadRequest)	if poaID == "" {	poaID := r.URL.Query().Get("poa_id")	}		return		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodGet {func (rws *RevocationWebService) HandleGetMetrics(w http.ResponseWriter, r *http.Request) {// GET /api/revocation/circuit/metrics?poa_id=poa-789// HandleGetMetrics retrieves circuit breaker metrics for a PoA// ============================================================================// CIRCUIT BREAKER HANDLERS// ============================================================================}	})		"state":   state,		"message": "Revocation challenged successfully, collateral slashed",		"status":  "challenged",	json.NewEncoder(w).Encode(map[string]interface{}{	w.WriteHeader(http.StatusOK)	w.Header().Set("Content-Type", "application/json")	state, _ := rws.optimistic.GetRevocationState(ctx, req.PoAID)	// Get updated state	}		return		http.Error(w, err.Error(), http.StatusInternalServerError)		rws.logger.Errorf("Failed to challenge PoA %s: %v", req.PoAID, err)	if err := rws.optimistic.ChallengeRevocation(ctx, req.PoAID, req.Challenger, req.Evidence); err != nil {	ctx := r.Context()	}		return		http.Error(w, "Missing required fields", http.StatusBadRequest)	if req.PoAID == "" || req.Challenger == "" || req.Evidence == "" {	}		return		http.Error(w, "Invalid request body", http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {	}		Evidence   string `json:"evidence"`		Challenger string `json:"challenger"`		PoAID      string `json:"poa_id"`	var req struct {	}		return		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (rws *RevocationWebService) HandleChallenge(w http.ResponseWriter, r *http.Request) {// Body: {"poa_id": "poa-456", "challenger": "validator-1", "evidence": "Transaction was legitimate"}// POST /api/revocation/optimistic/challenge// HandleChallenge challenges a pending revocation}	})		"state":   state,		"message": "PoA revocation finalized",		"status":  "finalized",	json.NewEncoder(w).Encode(map[string]interface{}{	w.WriteHeader(http.StatusOK)	w.Header().Set("Content-Type", "application/json")	state, _ := rws.optimistic.GetRevocationState(ctx, req.PoAID)	// Get updated state	}		return		http.Error(w, err.Error(), http.StatusInternalServerError)		rws.logger.Errorf("Failed to finalize PoA %s: %v", req.PoAID, err)	if err := rws.optimistic.FinalizeRevocation(ctx, req.PoAID); err != nil {	ctx := r.Context()	}		return		http.Error(w, "Missing poa_id", http.StatusBadRequest)	if req.PoAID == "" {	}		return		http.Error(w, "Invalid request body", http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {	}		PoAID string `json:"poa_id"`	var req struct {	}		return		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (rws *RevocationWebService) HandleFinalize(w http.ResponseWriter, r *http.Request) {// Body: {"poa_id": "poa-456"}// POST /api/revocation/optimistic/finalize// HandleFinalize finalizes a pending revocation}	})		"state":   state,		"message": "PoA marked as pending revocation",		"status":  "pending",	json.NewEncoder(w).Encode(map[string]interface{}{	w.WriteHeader(http.StatusOK)	w.Header().Set("Content-Type", "application/json")	state, _ := rws.optimistic.GetRevocationState(ctx, req.PoAID)	// Get updated state	}		return		http.Error(w, err.Error(), http.StatusInternalServerError)		rws.logger.Errorf("Failed to mark pending for PoA %s: %v", req.PoAID, err)	if err := rws.optimistic.MarkPendingRevocation(ctx, req.PoAID, req.Principal, req.Reason, req.Collateral); err != nil {	ctx := r.Context()	}		return		http.Error(w, "Missing required fields", http.StatusBadRequest)	if req.PoAID == "" || req.Principal == "" || req.Reason == "" || req.Collateral == 0 {	}		return		http.Error(w, "Invalid request body", http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {	}		Collateral uint64 `json:"collateral"`		Reason     string `json:"reason"`		Principal  string `json:"principal"`		PoAID      string `json:"poa_id"`	var req struct {	}		return		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (rws *RevocationWebService) HandleMarkPending(w http.ResponseWriter, r *http.Request) {// Body: {"poa_id": "poa-456", "principal": "bob", "reason": "Fraud", "collateral": 2000000000000000000}// POST /api/revocation/optimistic/pending// HandleMarkPending marks a PoA as pending revocation (with collateral)// ============================================================================// OPTIMISTIC REVOCATION HANDLERS// ============================================================================}	})		"message": "PoA re-enabled successfully",		"status":  "active",	json.NewEncoder(w).Encode(map[string]interface{}{	w.WriteHeader(http.StatusOK)	w.Header().Set("Content-Type", "application/json")	}		return		http.Error(w, err.Error(), http.StatusInternalServerError)		rws.logger.Errorf("Failed to cancel disable for PoA %s: %v", req.PoAID, err)	if err := rws.twoPhase.CancelDisable(ctx, req.PoAID); err != nil {	ctx := r.Context()	}		return		http.Error(w, "Missing poa_id", http.StatusBadRequest)	if req.PoAID == "" {	}		return		http.Error(w, "Invalid request body", http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {	}		PoAID string `json:"poa_id"`	var req struct {	}		return		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (rws *RevocationWebService) HandleCancelDisable(w http.ResponseWriter, r *http.Request) {// Body: {"poa_id": "poa-123"}// POST /api/revocation/cancel// HandleCancelDisable cancels a disabled PoA (returns to active)}	})		"state":   state,		"message": "PoA permanently revoked",		"status":  "revoked",	json.NewEncoder(w).Encode(map[string]interface{}{	w.WriteHeader(http.StatusOK)	w.Header().Set("Content-Type", "application/json")	state, _ := rws.twoPhase.GetPoAState(ctx, req.PoAID)	// Get updated state	}		return		http.Error(w, err.Error(), http.StatusInternalServerError)		rws.logger.Errorf("Failed to revoke PoA %s: %v", req.PoAID, err)	if err := rws.twoPhase.RevokePoA(ctx, req.PoAID, req.Reason); err != nil {	ctx := r.Context()	}		return		http.Error(w, "Missing required fields", http.StatusBadRequest)	if req.PoAID == "" || req.Reason == "" {	}		return		http.Error(w, "Invalid request body", http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {	}		Reason string `json:"reason"`		PoAID  string `json:"poa_id"`	var req struct {	}		return		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (rws *RevocationWebService) HandleRevokePoA(w http.ResponseWriter, r *http.Request) {// Body: {"poa_id": "poa-123", "reason": "Confirmed compromise"}// POST /api/revocation/revoke// HandleRevokePoA permanently revokes a PoA (Phase 2: irreversible)}	})		"state":   state,		"message": "PoA disabled successfully",		"status":  "disabled",	json.NewEncoder(w).Encode(map[string]interface{}{	w.WriteHeader(http.StatusOK)	w.Header().Set("Content-Type", "application/json")	state, _ := rws.twoPhase.GetPoAState(ctx, req.PoAID)	// Get updated state	}		return		http.Error(w, err.Error(), http.StatusInternalServerError)		rws.logger.Errorf("Failed to disable PoA %s: %v", req.PoAID, err)	if err := rws.twoPhase.DisablePoA(ctx, req.PoAID, req.Principal, req.Reason); err != nil {	ctx := r.Context()	}		return		http.Error(w, "Missing required fields", http.StatusBadRequest)	if req.PoAID == "" || req.Principal == "" || req.Reason == "" {	}		return		http.Error(w, "Invalid request body", http.StatusBadRequest)	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {	}		Reason    string `json:"reason"`		Principal string `json:"principal"`		PoAID     string `json:"poa_id"`	var req struct {	}		return		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)	if r.Method != http.MethodPost {func (rws *RevocationWebService) HandleDisablePoA(w http.ResponseWriter, r *http.Request) {// Body: {"poa_id": "poa-123", "principal": "alice", "reason": "Suspected compromise"}// POST /api/revocation/disable// HandleDisablePoA disables a PoA (Phase 1: reversible)// ============================================================================// TWO-PHASE REVOCATION HANDLERS// ============================================================================}	return nil	rws.oracle.Close()	rws.twoPhase.Close()	rws.optimistic.Close()	rws.circuitBreaker.Close()func (rws *RevocationWebService) Close() error {// Close gracefully shuts down all revocation systems}	mux.HandleFunc("/api/revocation/health", rws.HandleHealth)	// Health check	mux.HandleFunc("/api/revocation/validate", rws.HandleValidateTransaction)	// Transaction validation endpoint	mux.HandleFunc("/api/revocation/circuit/resume", rws.HandleManualResume)	mux.HandleFunc("/api/revocation/circuit/suspend", rws.HandleManualSuspend)	mux.HandleFunc("/api/revocation/circuit/reset", rws.HandleResetMetrics)	mux.HandleFunc("/api/revocation/circuit/metrics", rws.HandleGetMetrics)	// Circuit Breaker endpoints	mux.HandleFunc("/api/revocation/optimistic/challenge", rws.HandleChallenge)	mux.HandleFunc("/api/revocation/optimistic/finalize", rws.HandleFinalize)	mux.HandleFunc("/api/revocation/optimistic/pending", rws.HandleMarkPending)	// Optimistic Revocation endpoints	mux.HandleFunc("/api/revocation/status", rws.HandleGetStatus)	mux.HandleFunc("/api/revocation/cancel", rws.HandleCancelDisable)	mux.HandleFunc("/api/revocation/revoke", rws.HandleRevokePoA)	mux.HandleFunc("/api/revocation/disable", rws.HandleDisablePoA)	// Two-Phase Revocation endpointsfunc (rws *RevocationWebService) RegisterHandlers(mux *http.ServeMux) {// RegisterHandlers registers all HTTP handlers with the given mux}	}, nil		logger:         logger,		circuitBreaker: circuitBreaker,		optimistic:     optimistic,		twoPhase:       twoPhase,		oracle:         oracle,	return &RevocationWebService{	}()		}			logger.Errorf("Redis Pub/Sub listener stopped: %v", err)		if err := oracle.StartRedisPubSub(context.Background()); err != nil {	go func() {	// Start Redis Pub/Sub listener for cluster-wide revocations	circuitBreaker.SetRecoveryTestCount(10)	circuitBreaker.SetSuspensionDuration(5 * time.Minute)	}		return nil, fmt.Errorf("failed to create circuit breaker: %w", err)		oracle.Close()		twoPhase.Close()		optimistic.Close()	if err != nil {	circuitBreaker, err := revocation.NewCircuitBreaker(redisAddrs, config, logger)	}		FailureWindowSecs:  60,		MaxFailureRate:     0.1,   // 10% max failure rate		MaxValuePerHour:    1e20,  // 100 ETH per hour		MaxValuePerMinute:  1e19,  // 10 ETH per minute		MaxTxPerHour:       100,		MaxTxPerMinute:     10,	config := &revocation.RateLimitConfig{	// Initialize circuit breaker	optimistic.SetMinCollateral(1e18)                 // 1 ETH minimum collateral	optimistic.SetMempoolClearTime(60 * time.Second)  // 60 second mempool clear	optimistic.SetChallengeWindow(15 * time.Minute)   // 15 minute challenge window	}		return nil, fmt.Errorf("failed to create optimistic revocation: %w", err)		oracle.Close()		twoPhase.Close()	if err != nil {	optimistic, err := revocation.NewOptimisticRevocation(redisAddrs, oracle, logger)	// Initialize optimistic revocation	twoPhase.SetDisableTimeout(60 * time.Second) // 60 second cancellation window	}		return nil, fmt.Errorf("failed to create two-phase revocation: %w", err)		oracle.Close()	if err != nil {	twoPhase, err := revocation.NewTwoPhaseRevocation(oracle, redisAddrs, logger)	// Initialize two-phase revocation	}		return nil, fmt.Errorf("failed to create oracle: %w", err)	if err != nil {	oracle, err := revocation.NewEmergencyOracle(redisAddrs, logger)	// Initialize emergency oraclefunc NewRevocationWebService(redisAddrs []string, logger revocation.Logger) (*RevocationWebService, error) {// NewRevocationWebService creates a new web service with all revocation systems initialized}	logger         revocation.Logger	circuitBreaker *revocation.CircuitBreaker	optimistic     *revocation.OptimisticRevocation	twoPhase       *revocation.TwoPhaseRevocation	oracle         *revocation.EmergencyRevocationOracletype RevocationWebService struct {// RevocationWebService wraps all revocation systems with HTTP handlers