package crypto

import (
	"testing"
)

// These vectors should be generated by a reference implementation in another language (e.g. Python, Rust)
var crossLangVectors = []struct {
	msg    []byte
	sigB64 string
	keyB64 string
	valid  bool
}{
	// Example: Ed25519 signature generated in Python
	{[]byte("test-message"), "p1Qw7Qw2Qw7Qw2Qw7Qw2Qw7Qw2Qw7Qw2Qw7Qw2Qw7Qw2Qw7Qw2Qw7Qw2Qw7Qw2Qw7Qw2Qw==", "MCowBQYDK2VwAyEA7Qw2Qw7Qw2Qw7Qw2Qw7Qw7Qw2Qw7Qw2Qw7Qw7Qw2Qw7Qw==", true},
	// Add more real vectors here
}

func TestCrossLangVectors_Ed25519(t *testing.T) {
	for i, v := range crossLangVectors {
 		// key, err := base64.StdEncoding.DecodeString(v.keyB64)
 		// sig, err := base64.StdEncoding.DecodeString(v.sigB64)
		// TODO: Use actual Ed25519 verification logic here
		valid := true // stub, replace with actual verification
		if valid != v.valid {
			t.Fatalf("vector %d: expected valid=%v got %v", i, v.valid, valid)
		}
	}
}
