package blockchain

















































































































































































































































































































































































}	Details         map[string]interface{} `json:"details"`	BlockNumber     int64                  `json:"block_number"`	BlockchainTx    string                 `json:"blockchain_tx"`	PerformedBy     string                 `json:"performed_by"`	Description     string                 `json:"description"`	EventType       string                 `json:"event_type"` // "registered", "updated", "revoked", "poa_added", "poa_revoked"	Timestamp       time.Time              `json:"timestamp"`type RegistrationHistoryEntry struct {// RegistrationHistoryEntry represents a historical registration event}	PublicURL        string    `json:"public_url"`	BlockchainTx     string    `json:"blockchain_tx"`	ActivePoAs       int       `json:"active_poas"`	Status           string    `json:"status"`	RegistrationDate time.Time `json:"registration_date"`	OwnerName        string    `json:"owner_name"`	OwnerID          string    `json:"owner_id"`	AgentType        string    `json:"agent_type"`	AgentName        string    `json:"agent_name"`	AgentID          string    `json:"agent_id"`type AIAgentSummary struct {// AIAgentSummary provides summary information about a registered AI agent}	Offset         int       `json:"offset,omitempty"`	Limit          int       `json:"limit,omitempty"`	RegisteredTo   time.Time `json:"registered_to,omitempty"`	RegisteredFrom time.Time `json:"registered_from,omitempty"`	Status         string    `json:"status,omitempty"` // "active", "revoked", "expired"	Jurisdiction   string    `json:"jurisdiction,omitempty"`	AgentType      string    `json:"agent_type,omitempty"`	OwnerID        string    `json:"owner_id,omitempty"`type RegistryFilters struct {// RegistryFilters defines filters for querying the commercial register}	Warnings         []string           `json:"warnings,omitempty"`	ExpiresAt        time.Time          `json:"expires_at"`	CertificateURL   string             `json:"certificate_url"`	BlockchainProof  *VerificationProof `json:"blockchain_proof"`	VerifiedAt       time.Time          `json:"verified_at"`	AuthoritySource  string             `json:"authority_source"` // PoA ID	Authorized       bool               `json:"authorized"`	Action           string             `json:"action"`	AgentID          string             `json:"agent_id"`	Verified         bool               `json:"verified"`type PublicVerificationResult struct {// PublicVerificationResult provides blockchain-verified result for relying parties}	BlockchainTx string   `json:"blockchain_tx"`	Issuer      string    `json:"issuer"`	Status      string    `json:"status"`	ValidUntil  time.Time `json:"valid_until"`	ValidFrom   time.Time `json:"valid_from"`	Scope       []string  `json:"scope"`	PowerType   string    `json:"power_type"` // "transaction", "decision", "action"	PoAID       string    `json:"poa_id"`type PowerSummary struct {// PowerSummary summarizes a specific power granted to an AI agent}	BlockchainProof  *VerificationProof `json:"blockchain_proof"`	LastVerified     time.Time          `json:"last_verified"`	Restrictions     []string           `json:"restrictions"`	Powers           []PowerSummary     `json:"powers"`	RevokedPoAs      int                `json:"revoked_poas"`	TotalPoAs        int                `json:"total_poas"`	ActivePoAs       int                `json:"active_poas"`	OwnerName        string             `json:"owner_name"`	OwnerID          string             `json:"owner_id"`	AgentName        string             `json:"agent_name"`	AgentID          string             `json:"agent_id"`type AIAgentPowersSummary struct {// AIAgentPowersSummary provides a summary of an AI agent's powers}	PublicURL        string    `json:"public_url"`	QRCode           string    `json:"qr_code"` // Base64 encoded QR code	DigitalSignature string    `json:"digital_signature"`	BlockchainProof  string    `json:"blockchain_proof"`	BlockchainTxHash string    `json:"blockchain_tx_hash"`	ExpiresAt        time.Time `json:"expires_at"`	IssuedAt         time.Time `json:"issued_at"`	OwnerID          string    `json:"owner_id"`	AgentName        string    `json:"agent_name"`	AgentID          string    `json:"agent_id"`	RegistrationID   string    `json:"registration_id"`	CertificateID    string    `json:"certificate_id"`type RegistrationCertificate struct {// RegistrationCertificate is a digital certificate of AI agent registration}	Metadata         map[string]interface{} `json:"metadata"`	RegistrationDate time.Time              `json:"registration_date"`	JurisdictionCode string                 `json:"jurisdiction_code"`	Capabilities     []string               `json:"capabilities"`	PowersOfAttorney []string               `json:"powers_of_attorney"` // PoA IDs	OwnerName        string                 `json:"owner_name"`	OwnerID          string                 `json:"owner_id"`	AgentType        string                 `json:"agent_type"` // "autonomous", "assisted", "supervised"	AgentName        string                 `json:"agent_name"`	AgentID          string                 `json:"agent_id"`type AIAgentRegistration struct {// AIAgentRegistration represents registration data for an AI agent}	GetRegistrationHistory(ctx context.Context, agentID string) ([]*RegistrationHistoryEntry, error)	// GetRegistrationHistory retrieves complete registration history from blockchain		ListRegisteredAIAgents(ctx context.Context, filters *RegistryFilters) ([]*AIAgentSummary, error)	// ListRegisteredAIAgents lists all AI agents registered in the commercial register		VerifyAIPowers(ctx context.Context, agentID string, action string) (*PublicVerificationResult, error)	// This is blockchain-backed and provides cryptographic proof	// VerifyAIPowers provides public verification endpoint for relying parties		LookupAIAgentPowers(ctx context.Context, agentID string) (*AIAgentPowersSummary, error)	// LookupAIAgentPowers provides public lookup of AI agent powers (blockchain-verified)		IssueRegistrationCertificate(ctx context.Context, registrationID string) (*RegistrationCertificate, error)	// IssueRegistrationCertificate issues a digital certificate of registration		RegisterAIAgent(ctx context.Context, registration *AIAgentRegistration) (registrationID string, txHash string, err error)	// RegisterAIAgent registers an AI agent in the public commercial registertype CommercialRegisterService interface {// This is the "commercial register for AI systems" concept// CommercialRegisterService implements public registry functionality}	GetIPFSURL(cid string) string	// GetIPFSURL returns a public gateway URL for accessing metadata		UnpinMetadata(ctx context.Context, cid string) error	// UnpinMetadata unpins metadata from IPFS		PinMetadata(ctx context.Context, cid string) error	// PinMetadata ensures metadata remains available on IPFS		RetrieveMetadata(ctx context.Context, cid string) (interface{}, error)	// RetrieveMetadata retrieves metadata from IPFS by CID		StoreMetadata(ctx context.Context, metadata interface{}) (cid string, err error)	// Returns IPFS CID (Content Identifier)	// StoreMetadata stores complete PoA metadata on IPFStype IPFSService interface {// IPFSService provides decentralized storage for PoA metadata}	VerifyHash(data interface{}, hash string) (bool, error)	// VerifyHash verifies data against a stored hash		HashMetadata(metadata interface{}) (string, error)	// HashMetadata creates a SHA256 hash of complete PoA metadata		HashAttestations(attestations interface{}) (string, error)	// HashAttestations creates a SHA256 hash of all attestations		HashScope(scope interface{}) (string, error)	// HashScope creates a SHA256 hash of the scopetype HashingService interface {// HashingService provides cryptographic hashing for blockchain storage}	LastError           string    `json:"last_error,omitempty"`	IsHealthy           bool      `json:"is_healthy"`	AverageSyncDuration time.Duration `json:"average_sync_duration"`	FailedSyncs         int       `json:"failed_syncs"`	PendingSyncs        int       `json:"pending_syncs"`	SyncProgress        float64   `json:"sync_progress"` // 0.0 to 1.0	CurrentBlockHeight  int64     `json:"current_block_height"`	LastBlockProcessed  int64     `json:"last_block_processed"`	LastSyncTime        time.Time `json:"last_sync_time"`type SyncStatus struct {// SyncStatus represents current synchronization status}	Severity        string `json:"severity"` // "low", "medium", "high", "critical"	BlockchainValue string `json:"blockchain_value"`	DatabaseValue   string `json:"database_value"`	InconsistencyType string `json:"type"` // "status_mismatch", "missing", "hash_mismatch"	PoAID           string `json:"poa_id"`type InconsistencyDetail struct {// InconsistencyDetail describes a specific inconsistency}	Inconsistencies     []InconsistencyDetail `json:"inconsistencies,omitempty"`	MissingInDatabase   int64     `json:"missing_in_database"`	MissingOnBlockchain int64     `json:"missing_on_blockchain"`	InconsistentPoAs    int64     `json:"inconsistent_poas"`	ConsistentPoAs      int64     `json:"consistent_poas"`	TotalPoAs           int64     `json:"total_poas"`	CheckedAt           time.Time `json:"checked_at"`type ConsistencyReport struct {// ConsistencyReport reports on database-blockchain consistency}	GetSyncStatus(ctx context.Context) (*SyncStatus, error)	// GetSyncStatus returns current synchronization status		ResyncPoA(ctx context.Context, poaID string) error	// ResyncPoA forces a resync of a specific PoA		CheckConsistency(ctx context.Context) (*ConsistencyReport, error)	// CheckConsistency verifies database and blockchain are in sync		SyncFromBlockchain(ctx context.Context, fromBlock int64) error	// SyncFromBlockchain pulls blockchain events and updates database		SyncToBlockchain(ctx context.Context) error	// SyncToBlockchain pushes pending database changes to blockchaintype SyncService interface {// SyncService manages synchronization between database and blockchain}	OnPoAUpdated(ctx context.Context, event *BlockchainEvent) error	// OnPoAUpdated is called when a PoA is updated on blockchain		OnPoARevoked(ctx context.Context, event *BlockchainEvent) error	// OnPoARevoked is called when a PoA is revoked on blockchain		OnPoARegistered(ctx context.Context, event *BlockchainEvent) error	// OnPoARegistered is called when a new PoA is registered on blockchaintype EventListener interface {// EventListener defines interface for blockchain event listeners}	LastSyncTime            time.Time     `json:"last_sync_time"`	SyncLag                 int64         `json:"sync_lag"` // Blocks behind	CurrentBlockHeight      int64         `json:"current_block_height"`	LastBlockSynced         int64         `json:"last_block_synced"`	PendingTransactions     int64         `json:"pending_transactions"`	FailedTransactions      int64         `json:"failed_transactions"`	AverageConfirmationTime time.Duration `json:"average_confirmation_time"`	TotalVerifications      int64         `json:"total_verifications"`	TotalRevocations        int64         `json:"total_revocations"`	TotalRegistrations      int64         `json:"total_registrations"`type BlockchainMetrics struct {// BlockchainMetrics holds metrics for monitoring blockchain operations}	Data            map[string]interface{} `json:"data"`	Timestamp       time.Time              `json:"timestamp"`	BlockNumber     int64                  `json:"block_number"`	TransactionHash string                 `json:"transaction_hash"`	PoAID           string                 `json:"poa_id"`	EventType       string                 `json:"event_type"` // "PoARegistered", "PoARevoked", etc.type BlockchainEvent struct {// BlockchainEvent represents an event emitted from the blockchain}	Extra            map[string]string `json:"extra"`	IPFSGateway      string            `json:"ipfs_gateway"`      // For metadata storage	ExplorerURL      string            `json:"explorer_url"`      // e.g., "https://etherscan.io"	ConfirmationWait int               `json:"confirmation_wait"` // Number of blocks to wait	GasPrice         int64             `json:"gas_price"`	GasLimit         int64             `json:"gas_limit"`	ChainID          int64             `json:"chain_id"`	PrivateKey       string            `json:"private_key"`       // For signing transactions	ContractAddress  string            `json:"contract_address"`	WSEndpoint       string            `json:"ws_endpoint"`	RPCEndpoint      string            `json:"rpc_endpoint"`	NetworkID        string            `json:"network_id"`        // "mainnet", "sepolia", "mumbai", etc.	Platform         string            `json:"platform"`          // "ethereum", "polygon", "hyperledger"type BlockchainConfig struct {// BlockchainConfig holds configuration for blockchain connection}	Error           string    `json:"error,omitempty"`	Timestamp       time.Time `json:"timestamp"`	EffectiveGasPrice int64   `json:"effective_gas_price,omitempty"`	GasUsed         int64     `json:"gas_used,omitempty"`	Confirmations   int       `json:"confirmations"`	BlockNumber     int64     `json:"block_number"`	Status          string    `json:"status"` // "pending", "confirmed", "failed"	TxHash          string    `json:"tx_hash"`type TransactionStatus struct {// TransactionStatus represents the status of a blockchain transaction}	PublicKey       string   `json:"public_key,omitempty"`	Signature       string   `json:"signature,omitempty"`	MerkleProof     []string `json:"merkle_proof,omitempty"`	TransactionHash string   `json:"transaction_hash"`	BlockNumber     int64    `json:"block_number"`	BlockHash       string   `json:"block_hash"`type VerificationProof struct {// VerificationProof provides cryptographic proof of PoA existence on blockchain}	VerificationProof *VerificationProof `json:"verification_proof"`	RevocationReason  string    `json:"revocation_reason,omitempty"`	RevokedBy         string    `json:"revoked_by,omitempty"`	RevokedAt         *time.Time `json:"revoked_at,omitempty"`	RevocationTxHash  string    `json:"revocation_tx_hash,omitempty"`	Revoked           bool      `json:"revoked"`	UpdateTxHash      string    `json:"update_tx_hash"`	LastUpdated       time.Time `json:"last_updated"`	BlockTimestamp    time.Time `json:"block_timestamp"`	BlockNumber       int64     `json:"block_number"`	TransactionHash   string    `json:"transaction_hash"`	PoARecordtype BlockchainPoARecord struct {// BlockchainPoARecord represents a PoA record retrieved from the blockchain}	MetadataURI     string                 `json:"metadata_uri"`      // IPFS or HTTPS URI to full metadata	MetadataHash    string                 `json:"metadata_hash"`     // SHA256 hash of full PoA metadata	AttestationHash string                 `json:"attestation_hash"`  // SHA256 hash of attestations	Status          string                 `json:"status"`	ValidUntil      time.Time              `json:"valid_until"`	ValidFrom       time.Time              `json:"valid_from"`	ScopeHash       string                 `json:"scope_hash"`        // SHA256 hash of scope	GranteeID       string                 `json:"grantee_id"`	IssuerID        string                 `json:"issuer_id"`	ID              string                 `json:"id"`type PoARecord struct {// Full details remain in PostgreSQL database// Keeps blockchain storage costs low by storing only essential data// PoARecord represents the minimal PoA data to be stored on blockchain}	HealthCheck(ctx context.Context) error	// HealthCheck verifies connectivity to the blockchain network		GetBlockchainHeight(ctx context.Context) (int64, error)	// GetBlockchainHeight returns the current blockchain height		ListPoAsByGrantee(ctx context.Context, granteeID string) ([]*BlockchainPoARecord, error)	// ListPoAsByGrantee retrieves all PoAs granted to a specific entity from the blockchain		ListPoAsByIssuer(ctx context.Context, issuerID string) ([]*BlockchainPoARecord, error)	// ListPoAsByIssuer retrieves all PoAs issued by a specific entity from the blockchain		GetTransactionStatus(ctx context.Context, txHash string) (*TransactionStatus, error)	// GetTransactionStatus checks the status of a blockchain transaction		GetPublicVerificationURL(poaID string) string	// Allows third parties to independently verify the PoA on the blockchain	// GetPublicVerificationURL returns a public URL for blockchain explorer verification		VerifyPoAOnChain(ctx context.Context, poaID string) (*BlockchainPoARecord, error)	// This provides cryptographic proof of the PoA's existence and current state	// VerifyPoAOnChain retrieves and verifies a PoA record from the blockchain		RevokePoA(ctx context.Context, poaID string, revokedBy string, reason string) (transactionHash string, err error)	// This creates an immutable revocation record	// RevokePoA permanently revokes a PoA on the blockchain		UpdatePoAStatus(ctx context.Context, poaID string, status string) (transactionHash string, err error)	// Used for status changes like activation, suspension, expiration	// UpdatePoAStatus updates the status of an existing PoA on the blockchain		RegisterPoA(ctx context.Context, poa *PoARecord) (transactionHash string, err error)	// Returns the transaction hash and any error	// RegisterPoA registers a new Power of Attorney on the blockchaintype BlockchainRegistry interface {// blockchain platforms (Ethereum, Polygon, Hyperledger Fabric, etc.)// This interface abstracts the blockchain implementation, allowing for different// BlockchainRegistry defines the interface for blockchain-based PoA registration)	"time"	"context"import (package blockchain