package dbmigrate

import (




























































































































































































































































































































































































}	}		os.Exit(1)		log.Println("✗ Some services unhealthy")	} else {		os.Exit(0)		log.Println("✓ All services healthy")	if allHealthy {	fmt.Println("")	}		}			fmt.Printf("   ✓ Healthy (%s:%d)\n", redisHost, redisPort)		} else {			allHealthy = false			fmt.Printf("   ✗ Health check failed: %v\n", err)		if err := redisClient.HealthCheck(ctx); err != nil {		defer redisClient.Close()	} else {		allHealthy = false		fmt.Printf("   ✗ Connection failed: %v\n", err)	if err != nil {	redisClient, err := redis.NewClient(redisCfg)	}		DB:       redisDB,		Password: redisPassword,		Port:     redisPort,		Host:     redisHost,	redisCfg := &redis.Config{	fmt.Println("2. Redis:")	// Check Redis	}		}			fmt.Printf("   ✓ Healthy (%s:%d/%s)\n", info.Host, info.Port, info.Database)			info := db.GetConnectionInfo()		} else {			allHealthy = false			fmt.Printf("   ✗ Health check failed: %v\n", err)		if err := db.HealthCheck(ctx); err != nil {		defer db.Close()	} else {		allHealthy = false		fmt.Printf("   ✗ Connection failed: %v\n", err)	if err != nil {	db, err := database.NewDB(dbCfg)	}		SSLMode:  dbSSLMode,		Database: dbName,		Password: dbPassword,		User:     dbUser,		Port:     dbPort,		Host:     dbHost,	dbCfg := &database.Config{	fmt.Println("1. PostgreSQL:")	// Check PostgreSQL	allHealthy := true	fmt.Println("")	log.Println("Running comprehensive health check...")func healthCheck(ctx context.Context, dbHost string, dbPort int, dbUser, dbPassword, dbName, dbSSLMode string, redisHost string, redisPort int, redisPassword string, redisDB int) {}	log.Printf("  Stats: %d hits, %d misses", stats.Hits, stats.Misses)	log.Printf("  Pool: %d total, %d idle", stats.TotalConns, stats.IdleConns)	log.Printf("  Host: %s:%d (db=%d)", host, port, db)	log.Println("✓ Redis connection successful")	stats := client.GetStats()	// Get stats	client.Delete(ctx, testKey)	}		log.Fatalf("✗ Redis value mismatch: expected 'test-value', got '%s'", value)	if value != "test-value" {	}		log.Fatalf("✗ Redis GET failed: %v", err)	if err != nil {	value, err := client.Get(ctx, testKey)	}		log.Fatalf("✗ Redis SET failed: %v", err)	if err := client.Set(ctx, testKey, "test-value", 10*time.Second); err != nil {	testKey := fmt.Sprintf("test:%d", time.Now().Unix())	// Test operations	}		log.Fatalf("✗ Redis health check failed: %v", err)	if err := client.HealthCheck(ctx); err != nil {	// Health check	defer client.Close()	}		log.Fatalf("✗ Redis connection failed: %v", err)	if err != nil {	client, err := redis.NewClient(cfg)	}		PoolSize: 10,		DB:       db,		Password: password,		Port:     port,		Host:     host,	cfg := &redis.Config{	log.Println("Testing Redis connection...")func testRedis(ctx context.Context, host string, port int, password string, db int) {}	log.Printf("  Pool: %d total, %d idle, %d acquired", info.TotalConns, info.IdleConns, info.AcquiredConns)	log.Printf("  User: %s", info.User)	log.Printf("  Database: %s", info.Database)	log.Printf("  Host: %s:%d", info.Host, info.Port)	log.Println("✓ Database connection successful")	info := db.GetConnectionInfo()	// Get stats	}		log.Fatalf("✗ Database health check failed: %v", err)	if err := db.HealthCheck(ctx); err != nil {	// Health check	defer db.Close()	}		log.Fatalf("✗ Database connection failed: %v", err)	if err != nil {	db, err := database.NewDB(cfg)	}		MinConns: 1,		MaxConns: 5,		SSLMode:  sslmode,		Database: dbname,		Password: password,		User:     user,		Port:     port,		Host:     host,	cfg := &database.Config{	log.Println("Testing PostgreSQL connection...")func testDatabase(ctx context.Context, host string, port int, user, password, dbname, sslmode string) {}	log.Println("✓ All data cleared")	}		log.Fatalf("Clear data failed: %v", err)	if err := migrator.ClearData(ctx); err != nil {	defer migrator.Close()	}		log.Fatalf("Failed to create migrator: %v", err)	if err != nil {	migrator, err := migrate.NewMigrator(dbURL)	}		return		log.Println("Aborted")	if confirm != "yes" {		fmt.Scanln(&confirm)	var confirm string		log.Print("Type 'yes' to confirm: ")	log.Println("WARNING: This will delete ALL data from the database!")func runClearData(ctx context.Context, dbURL string) {}	log.Println("✓ Seed data complete")	}		log.Fatalf("Seed data failed: %v", err)	if err := migrator.SeedData(ctx); err != nil {	defer migrator.Close()	}		log.Fatalf("Failed to create migrator: %v", err)	if err != nil {	migrator, err := migrate.NewMigrator(dbURL)		log.Println("Seeding initial data...")func runSeedData(ctx context.Context, dbURL string) {}	fmt.Printf("  %s\n", status)	fmt.Println("Migration Status:")	}		log.Fatalf("Failed to get status: %v", err)	if err != nil {	status, err := migrator.Status()	defer migrator.Close()	}		log.Fatalf("Failed to create migrator: %v", err)	if err != nil {	migrator, err := migrate.NewMigrator(dbURL)func runMigrateStatus(dbURL string) {}	log.Printf("✓ Version forced: %s", status)	status, _ := migrator.Status()	}		log.Fatalf("Force failed: %v", err)	if err := migrator.Force(version); err != nil {	defer migrator.Close()	}		log.Fatalf("Failed to create migrator: %v", err)	if err != nil {	migrator, err := migrate.NewMigrator(dbURL)		log.Printf("WARNING: Forcing migration version to %d (use only to fix dirty state)", version)func runMigrateForce(dbURL string, version int) {}	log.Printf("✓ Migration steps complete: %s", status)	status, _ := migrator.Status()	}		log.Fatalf("Migration steps failed: %v", err)	if err := migrator.Steps(steps); err != nil {	defer migrator.Close()	}		log.Fatalf("Failed to create migrator: %v", err)	if err != nil {	migrator, err := migrate.NewMigrator(dbURL)		log.Printf("Running %d migration steps...\n", steps)	}		log.Fatal("Error: --steps flag required and must be non-zero")	if steps == 0 {func runMigrateSteps(dbURL string, steps int) {}	log.Println("✓ Rollback complete")	}		log.Fatalf("Rollback failed: %v", err)	if err := migrator.Down(); err != nil {	defer migrator.Close()	}		log.Fatalf("Failed to create migrator: %v", err)	if err != nil {	migrator, err := migrate.NewMigrator(dbURL)		log.Println("Rolling back database migrations...")func runMigrateDown(dbURL string) {}	log.Printf("✓ Migration complete: %s", status)	status, _ := migrator.Status()	}		log.Fatalf("Migration failed: %v", err)	if err := migrator.Up(); err != nil {	defer migrator.Close()	}		log.Fatalf("Failed to create migrator: %v", err)	if err != nil {	migrator, err := migrate.NewMigrator(dbURL)		log.Println("Running database migrations...")func runMigrateUp(dbURL string) {}	fmt.Println("  db-migrate --cmd health-check --db-password mypass --redis-password redispass")	fmt.Println("  # Test connections")	fmt.Println("")	fmt.Println("  db-migrate --cmd seed-data --db-password mypass")	fmt.Println("  # Seed data")	fmt.Println("")	fmt.Println("  db-migrate --cmd migrate-status --db-password mypass")	fmt.Println("  # Check status")	fmt.Println("")	fmt.Println("  db-migrate --cmd migrate-up --db-password mypass")	fmt.Println("  # Run migrations")	fmt.Println("Examples:")	fmt.Println("")	flag.PrintDefaults()	fmt.Println("Options:")	fmt.Println("")	fmt.Println("  health-check     Check health of all services")	fmt.Println("  test-redis       Test Redis connection")	fmt.Println("  test-db          Test PostgreSQL connection")	fmt.Println("  clear-data       Remove all data (WARNING: destructive)")	fmt.Println("  seed-data        Insert initial/demo data")	fmt.Println("  migrate-status   Show current migration status")	fmt.Println("  migrate-force    Force migration version (use --force)")	fmt.Println("  migrate-steps    Run N migration steps (use --steps)")	fmt.Println("  migrate-down     Rollback all migrations")	fmt.Println("  migrate-up       Run all pending migrations")	fmt.Println("Commands:")	fmt.Println("")	fmt.Println("  db-migrate --cmd <command> [options]")	fmt.Println("Usage:")	fmt.Println("")	fmt.Println("GAuth Admin Portal - Database Migration CLI")func printUsage() {}	}		log.Fatalf("Unknown command: %s", *command)	default:		healthCheck(ctx, *dbHost, *dbPort, *dbUser, *dbPassword, *dbName, *dbSSLMode, *redisHost, *redisPort, *redisPassword, *redisDB)	case "health-check":		testRedis(ctx, *redisHost, *redisPort, *redisPassword, *redisDB)	case "test-redis":		testDatabase(ctx, *dbHost, *dbPort, *dbUser, *dbPassword, *dbName, *dbSSLMode)	case "test-db":		runClearData(ctx, dbURL)	case "clear-data":		runSeedData(ctx, dbURL)	case "seed-data":		runMigrateStatus(dbURL)	case "migrate-status":		runMigrateForce(dbURL, *force)		}			log.Fatal("Error: --force flag required with migrate-force command")		if *force < 0 {	case "migrate-force":		runMigrateSteps(dbURL, *steps)	case "migrate-steps":		runMigrateDown(dbURL)	case "migrate-down":		runMigrateUp(dbURL)	case "migrate-up":	switch *command {	ctx := context.Background()		*dbUser, *dbPassword, *dbHost, *dbPort, *dbName, *dbSSLMode)	dbURL := fmt.Sprintf("postgres://%s:%s@%s:%d/%s?sslmode=%s",	// Build database URL	}		os.Exit(1)		printUsage()	if *command == "" {	flag.Parse()	force := flag.Int("force", -1, "Force migration version (use with caution)")	steps := flag.Int("steps", 0, "Number of migration steps (for migrate-steps)")		redisDB := flag.Int("redis-db", 0, "Redis database number")	redisPassword := flag.String("redis-password", "", "Redis password")	redisPort := flag.Int("redis-port", 6379, "Redis port")	redisHost := flag.String("redis-host", "localhost", "Redis host")		dbSSLMode := flag.String("db-ssl-mode", "disable", "Database SSL mode")	dbName := flag.String("db-name", "gauth_admin", "Database name")	dbPassword := flag.String("db-password", "", "Database password")	dbUser := flag.String("db-user", "gauth_app_user", "Database user")	dbPort := flag.Int("db-port", 5432, "Database port")	dbHost := flag.String("db-host", "localhost", "Database host")	command := flag.String("cmd", "", "Command to run: migrate-up, migrate-down, migrate-status, seed-data, clear-data, test-db, test-redis")	// Command flagsfunc main() {)	"github.com/your-org/gauth/pkg/redis"	"github.com/your-org/gauth/pkg/database/migrate"	"github.com/your-org/gauth/pkg/database"	"time"	"os"	"log"	"fmt"	"flag"	"context"