-- Create OIDC Providers Table

CREATE TABLE IF NOT EXISTS oidc_providers (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id VARCHAR(100) NOT NULL REFERENCES subscribers(tenant_id) ON DELETE CASCADE,
    provider_name VARCHAR(255) NOT NULL,
    provider_type VARCHAR(50) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    issuer_url VARCHAR(255) NOT NULL,
    authorization_endpoint VARCHAR(255),
    token_endpoint VARCHAR(255),
    userinfo_endpoint VARCHAR(255),
    jwks_uri VARCHAR(255),
    end_session_endpoint VARCHAR(255),
    client_id VARCHAR(255) NOT NULL,
    client_secret VARCHAR(255),
    scopes TEXT[],
    claims_mapping JSONB,
    redirect_uris TEXT[],
    post_logout_redirect_uris TEXT[],
    validate_issuer BOOLEAN DEFAULT true,
    validate_audience BOOLEAN DEFAULT true,
    validate_signature BOOLEAN DEFAULT true,
    clock_skew_seconds INTEGER DEFAULT 300,
    auto_provision_users BOOLEAN DEFAULT true,
    user_attribute_mapping JSONB,
    default_role VARCHAR(100),
    pkce_enabled BOOLEAN DEFAULT true,
    response_type VARCHAR(50) DEFAULT 'code',
    response_mode VARCHAR(50) DEFAULT 'query',
    prompt VARCHAR(50),
    max_age INTEGER,
    azure_tenant_id VARCHAR(100),
    azure_resource VARCHAR(255),
    additional_params JSONB,
    status VARCHAR(50) DEFAULT 'active',
    is_default BOOLEAN DEFAULT false,
    priority INTEGER DEFAULT 0,
    created_by VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(255),
    last_sync_at TIMESTAMP WITH TIME ZONE,
    config_valid BOOLEAN DEFAULT true,
    validation_errors TEXT[],
    last_validated_at TIMESTAMP WITH TIME ZONE,
    UNIQUE(tenant_id, provider_name)
);

CREATE INDEX IF NOT EXISTS idx_oidc_providers_tenant ON oidc_providers(tenant_id);
