package webhook
package webhook

import (
	"time"
)























































































































































}	Offset    int            `form:"offset"`	Limit     int            `form:"limit"`	Status    DeliveryStatus `form:"status"`	EventType string         `form:"event_type"`	WebhookID string         `form:"webhook_id"`type ListDeliveriesQuery struct {// ListDeliveriesQuery represents query parameters for listing deliveries}	Offset  int    `form:"offset"`	Limit   int    `form:"limit"`	Enabled *bool  `form:"enabled"`	UserID  string `form:"user_id"`type ListWebhooksQuery struct {// ListWebhooksQuery represents query parameters for listing webhooks}	Secret string `json:"secret,omitempty"` // Only included on creation	Webhooktype WebhookResponse struct {// WebhookResponse represents a webhook in API responses (includes secret on creation)}	Timeout     *int               `json:"timeout_seconds,omitempty"`	RetryCount  *int               `json:"retry_count,omitempty"`	Headers     map[string]string  `json:"headers,omitempty"`	Description *string            `json:"description,omitempty"`	Enabled     *bool              `json:"enabled,omitempty"`	Events      []string           `json:"events,omitempty"`	URL         *string            `json:"url,omitempty"`	Name        *string            `json:"name,omitempty"`type UpdateWebhookRequest struct {// UpdateWebhookRequest represents a request to update a webhook}	Timeout     int               `json:"timeout_seconds,omitempty"` // Default: 30	RetryCount  int               `json:"retry_count,omitempty"` // Default: 3	Headers     map[string]string `json:"headers,omitempty"`	Description string            `json:"description,omitempty"`	Events      []string          `json:"events" binding:"required,min=1"`	URL         string            `json:"url" binding:"required,url"`	Name        string            `json:"name" binding:"required"`type CreateWebhookRequest struct {// CreateWebhookRequest represents a request to create a webhook}	SuccessRatePercent   *float64  `json:"success_rate_percent,omitempty" db:"success_rate_percent"`	LastDeliveryAt       *time.Time `json:"last_delivery_at,omitempty" db:"last_delivery_at"`	AvgDurationMs        *float64  `json:"avg_duration_ms,omitempty" db:"avg_duration_ms"`	RetryingDeliveries   int       `json:"retrying_deliveries" db:"retrying_deliveries"`	FailedDeliveries     int       `json:"failed_deliveries" db:"failed_deliveries"`	SuccessfulDeliveries int       `json:"successful_deliveries" db:"successful_deliveries"`	TotalDeliveries      int       `json:"total_deliveries" db:"total_deliveries"`	Enabled              bool      `json:"enabled" db:"enabled"`	URL                  string    `json:"url" db:"url"`	Name                 string    `json:"name" db:"name"`	WebhookID            string    `json:"webhook_id" db:"webhook_id"`type WebhookStats struct {// WebhookStats represents delivery statistics for a webhook}	Data      map[string]interface{} `json:"data"`	UserID    string                 `json:"user_id"`	Timestamp time.Time              `json:"timestamp"`	Type      EventType              `json:"type"`	ID        string                 `json:"id"`type Event struct {// Event represents a webhook event to be dispatched}	DurationMs    *int                   `json:"duration_ms,omitempty" db:"duration_ms"`	NextRetryAt   *time.Time             `json:"next_retry_at,omitempty" db:"next_retry_at"`	CompletedAt   *time.Time             `json:"completed_at,omitempty" db:"completed_at"`	SentAt        *time.Time             `json:"sent_at,omitempty" db:"sent_at"`	CreatedAt     time.Time              `json:"created_at" db:"created_at"`	ErrorMessage  string                 `json:"error_message,omitempty" db:"error_message"`	MaxAttempts   int                    `json:"max_attempts" db:"max_attempts"`	AttemptNumber int                    `json:"attempt_number" db:"attempt_number"`	Status        DeliveryStatus         `json:"status" db:"status"`	ResponseHeaders map[string]string    `json:"response_headers,omitempty" db:"response_headers"`	ResponseBody  string                 `json:"response_body,omitempty" db:"response_body"`	StatusCode    *int                   `json:"status_code,omitempty" db:"status_code"`	Payload       map[string]interface{} `json:"payload" db:"payload"`	Headers       map[string]string      `json:"headers,omitempty" db:"headers"`	HTTPMethod    string                 `json:"http_method" db:"http_method"`	URL           string                 `json:"url" db:"url"`	EventType     string                 `json:"event_type" db:"event_type"`	EventID       string                 `json:"event_id" db:"event_id"`	WebhookID     string                 `json:"webhook_id" db:"webhook_id"`	ID            string                 `json:"id" db:"id"`type WebhookDelivery struct {// WebhookDelivery represents a webhook delivery attempt}	LastTriggeredAt  *time.Time `json:"last_triggered_at,omitempty" db:"last_triggered_at"`	UpdatedAt        time.Time  `json:"updated_at" db:"updated_at"`	CreatedAt        time.Time  `json:"created_at" db:"created_at"`	Headers     map[string]string `json:"headers,omitempty" db:"headers"`	Description string            `json:"description,omitempty" db:"description"`	Timeout     int               `json:"timeout_seconds" db:"timeout_seconds"`	RetryCount  int               `json:"retry_count" db:"retry_count"`	Events      []string          `json:"events" db:"events"`	Enabled     bool              `json:"enabled" db:"enabled"`	UserID      string            `json:"user_id" db:"user_id"`	Secret      string            `json:"-" db:"secret"` // Never expose in JSON	URL         string            `json:"url" db:"url"`	Name        string            `json:"name" db:"name"`	ID          string            `json:"id" db:"id"`type Webhook struct {// Webhook represents a webhook registration)	DeliveryStatusRetrying DeliveryStatus = "retrying"	DeliveryStatusFailed   DeliveryStatus = "failed"	DeliveryStatusSuccess  DeliveryStatus = "success"	DeliveryStatusPending  DeliveryStatus = "pending"const (type DeliveryStatus string// DeliveryStatus represents the status of a webhook delivery)	EventBlockchainSyncFailed    EventType = "blockchain.sync_failed"	EventBlockchainSyncCompleted EventType = "blockchain.sync_completed"	// Blockchain Events	EventDualControlRejected         EventType = "dual_control.rejected"	EventDualControlApproved         EventType = "dual_control.approved"	EventDualControlApprovalRequired EventType = "dual_control.approval_required"	// Dual Control Events	EventDelegationRevoked EventType = "delegation.revoked"	EventDelegationCreated EventType = "delegation.created"	// Delegation Events	EventSuccessorActivated EventType = "successor.activated"	// Successor Events	EventPoAExpired  EventType = "poa.expired"	EventPoAVerified EventType = "poa.verified"	EventPoARevoked  EventType = "poa.revoked"	EventPoAUpdated  EventType = "poa.updated"	EventPoACreated  EventType = "poa.created"	// PoA Eventsconst (type EventType string// EventType represents the type of webhook event