theme: jekyll-theme-minimal
title: "GAuth Protocol Demonstrations"
description: "Interactive demonstrations of the revolutionary GAuth Protocol (RFC111 & RFC115)"
baseurl: "/GiFo-RFC-0150-Go-Implementation-of-GAuth-1.0"
url: "https://gimel-foundation.github.io"

# Enable GitHub Pages
plugins:
  - jekyll-relative-links
  - jekyll-optional-front-matter

relative_links:
  enabled: true
  collections: true

include:
  - index.html
  - rfc111-benefits-showcase.html
  - rfc111-rfc115-paradigm-showcase.html
