//go:build ignore

package main

import (
	"bufio"
	"encoding/csv"
	"fmt"
	"log"
	"os"
	"sort"
	"strings"
)

// Columns expected in artifacts/gap_matrix.csv:
// Section,ID,Requirement,Status,Priority,Gap,Evidence

type row struct {
    Section     string
    ID          string
    Requirement string
    Status      string
    Priority    string
    Gap         string
    Evidence    string
}

func main() {
    f, err := os.Open("artifacts/gap_matrix.csv")
    if err != nil {
        log.Fatalf("open csv: %v", err)
    }
    defer f.Close()
    r := csv.NewReader(bufio.NewReader(f))
    r.FieldsPerRecord = -1
    records, err := r.ReadAll()
    if err != nil {
        log.Fatalf("read csv: %v", err)
    }
    var rows []row
    for _, rec := range records {
        if len(rec) == 0 || strings.HasPrefix(strings.TrimSpace(rec[0]), "#") || strings.EqualFold(rec[0], "Section") {
            continue
        }
        // Pad missing columns if any (defensive)
        for len(rec) < 7 { rec = append(rec, "") }
        rows = append(rows, row{Section: rec[0], ID: rec[1], Requirement: rec[2], Status: rec[3], Priority: rec[4], Gap: rec[5], Evidence: rec[6]})
    }

    // Stable ordering: by ID (secX.itemY numeric) to keep diffs minimal.
    sort.Slice(rows, func(i, j int) bool { return rows[i].ID < rows[j].ID })

    // Emit markdown
    fmt.Println("# GAP Matrix (Auto-Generated)\n")
    fmt.Println("| ID | Requirement | Status | Priority | Gap | Evidence |")
    fmt.Println("|----|-------------|--------|----------|-----|----------|")
    for _, rw := range rows {
        // Escape pipe characters in free text cells
        gap := strings.ReplaceAll(rw.Gap, "|", "\\|")
        evidence := strings.ReplaceAll(rw.Evidence, "|", "\\|")
        req := strings.ReplaceAll(rw.Requirement, "|", "\\|")
        fmt.Printf("| %s | %s | %s | %s | %s | %s |\n", rw.ID, req, rw.Status, rw.Priority, gap, evidence)
    }
    fmt.Println("\n> Source: artifacts/gap_matrix.csv (do not edit this file manually). Regenerate via: `go run scripts/gen_gap_matrix_auto.go > docs/GAP_MATRIX.auto.md`.")
}
